### ISSUE TITLE
Navbar has disappeared after scrolling  

### ISSUE THREAD

**Issue by kerrtravers** [GreenBayRules/quark-editor#3]
### Issue 
I posted some HTML code in the editor (when set to HTML) and the navbar is now gone, even after refreshing the page. I think this is something to do with the way the editor handles scrolling and longer text.

![untitled](https://user-images.githubusercontent.com/26391179/35286229-4ffc5cc0-0057-11e8-8161-2771de459e86.png)

### Steps to reproduce 
Paste HTML text long enough for the page to scroll down, then try and get back to the top with the navbar.

**Comment by Sheshank-s** [comment]
Do you mean the scrollbar?

Because I don't seee any problem with the nav. I rememoved the scroll bar because it didn't look very good.

**Comment by kerrtravers** [comment]
@GreenBayRules No, the whole blue navigation is gone.

**Comment by Sheshank-s** [comment]
Can you show me a screenshot, give me your browser too?

**Comment by kerrtravers** [comment]
It's probably best to show you:
![untitled](https://user-images.githubusercontent.com/26391179/35298340-c42379ae-0079-11e8-8ef8-6d4c7eb6d559.gif)

(Notice that when I'm scrolling back to the top, the navbar isn't there?)

MacOS High Sierra, Chrome 63.0.3239.132

**Comment by Sheshank-s** [comment]
I don't see anything there..

**Comment by kerrtravers** [comment]
Let the GIF load.

**Comment by Sheshank-s** [comment]
Oh i see now. I can replicate on my computer.

**Comment by kerrtravers** [comment]
Yeah 😸

**Comment by Sheshank-s** [comment]
@vutondesign Can you try an identify the problem?

**Comment by kerrtravers** [comment]
@GreenBayRules Maybe try making the navbar sticky?

**Comment by Sheshank-s** [comment]
I'm at school right now, can you try it locally and see if it works?23.01.2018, 12:34, "Kerr Travers" <notifications@github.com>:@GreenBayRules Maybe try making the navbar sticky?

**Comment by Sheshank-s** [comment]
Fixed!

**Comment by kerrtravers** [comment]
Nice 👍
