### ISSUE TITLE
Make a new theme that uses atom colors

### ISSUE THREAD

**Issue by Sheshank-s** [GreenBayRules/quark-editor#5]
Make a new theme that uses the dark colors of atom

**Comment by Sheshank-s** [comment]
I'll mark this as help wanted, and if it doesn't get completed in a while ill do it myself

**Comment by radioblahaj** [comment]
What is the colour theme
pattle you would want to use?

**Comment by Sheshank-s** [comment]
Never mind i did this already

**Comment by radioblahaj** [comment]
k
